call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'

call plug#end()

set number
set linebreak
set showmatch
set cursorline

set ignorecase

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set cc=80

syntax on

set bg=dark
colorscheme gruvbox
